
from django.contrib import admin
from django.urls import include, path
from . import  views
urlpatterns = [
    path('login_load/',views.login_load),
    path('login_load_post/',views.login_load_post),
    path('admin_home/',views.admin_home),
    path('admin_adddepartment/',views.admin_adddepartment),
    path('admin_adddepartment_post/',views.adddepartment_post),
    path('admin_addschedule/', views.admin_addschedule),
    path('admin_addschedule_post/', views.addschedule_post),
    path('admin_adddisease', views.admin_adddisease),
    path('admin_adddisease_post', views.adddisease_post),
    path('admin_adddoctor', views.admin_adddoctor),
    path('admin_adddoctor_post', views.adddoctor_post),
    path('admin_addsymptoms', views.admin_addsymptoms),
    path('admin_addsymptoms_post', views.addsymptoms_post),
    path('admin_changepassword', views.admin_changepassword),
    path('admin_viewdisease', views.admin_viewdisease),
    path('viewdisease', views.viewdisease),
    path('delete_disease/<int:id>', views.delete_disease),
    path('edit_disease/<int:id>', views.edit_disease),
    path('admin_edit_disease_post', views.edit_disease_post),
    path('admin_viewdoctor', views.admin_viewdoctor),
    path('viewdoctor_post', views.viewdoctor_post),
    path('delete_doctor/<int:id>', views.delete_doctor),
    path('edit_doctor/<int:id>', views.edit_doctor),
    path('admin_edit_doctor_post', views.edit_doctor_post),
    path('admin_viewshedule', views.admin_viewshedule),
    path('viewschedule_post', views.viewschedule_post),
    path('delete_schedule/<int:id>', views.delete_schedule),
    path('edit_schedule/<int:id>', views.edit_schedule),
    path('admin_edit_schedule_post', views.edit_schedule_post),
    path('admin_viewdepartment', views.admin_viewdepartment),
    path('viewdepartment_post', views.viewdepartment_post),
    path('delete_department/<int:id>', views.delete_department),
    path('edit_department/<int:id>', views.edit_department),
    path('admin_edit_department_post', views.edit_department_post),
    path('admin_viewsymptoms', views.admin_viewsymptoms),
    path('viewsymptoms_post', views.viewsymptoms_post),
    path('delete_symptoms/<int:id>', views.delete_symptoms),
    path('edit_symptoms/<int:id>', views.edit_symptoms),
    path('admin_edit_symptoms_post', views.edit_symptoms_post),
    path('admin_viewfeedback', views.admin_viewfeedback),
    path('admin_viewpayment', views.admin_viewpayments),
    path('viewpayments_post', views.viewpayments_post),
    path('admin_chat_to_doctor', views.admin_chat_to_doctor),
    path('admin_doctor_payment', views.admin_doctor_payment),
    path('admin_chat_with_doctor/<id>', views.admin_chat_with_doctor),

    path('admin_view_msg/<receiverid>', views.admin_view_msg),
    path('admin_insert_chat/<receiverid>/<msg>/<senid>', views.admin_insert_chat),
    path('chatv/<dlid>', views.chatv),




    path('doctor_home',views.doctor_home),
    path('doctor_viewmyfeedback',views.doctor_viewmyfeedback),
    path('doctor_viewpaymentsofdoctor',views.doctor_viewpaymentsofdoctor),
    path('doctor_viewmybooking',views.doctor_viewmybooking),
    path('view_booking_post',views.view_booking_post),
    path('doctor_viewmyschedule',views.doctor_viewmyschedule),
    path('doctor_viewpatient/<sid>',views.doctor_viewpatient),
    path('doctor_chat_with_patient/<ID>',views.doctor_chat_with_patient),
    path('doc_view_msg/<receiverid>',views.doc_view_msg),
    path('doctor_chat_with_admin',views.doctor_chat_with_admin),
    path('doctor_doctor_profile', views.doctor_doctor_profile),
    # path('doctor_viewpatients/<pid>', views.doctor_viewpatients),
    path('doctor_Viewpatients/',views.doctor_Viewpatients),
    path('chatview_dtop/', views.chatview_dtop),
    path('doc_view_msg/<receiverid>', views.doc_view_msg),

    path('doc_view_msg/<receiverid>', views.doc_view_msg),
    path('doc_insert_chat/<receiverid>/<msg>/<senid>', views.doc_insert_chat),
    path('chatviewdoc/<dlid>', views.chatviewdoc),

    path('patient_home',views.patient_home),
    path('patient_booking/<bok>',views.patient_booking),
    path('patient_registration',views.patient_registration),
    path('patient_registration_post',views.registration_post),
    path('patient_view_doctor',views.patient_view_doctor),
    path('view_doctor_post',views.view_doctor_post),
    path('patient_view_schedule/<did>',views.patient_view_schedule),
    path('patient_chat_with_doctor/<dlid>',views.patient_chat_with_doctor),
    path('patient_payment',views.patient_payment),
    path('patient_send_feedback_abt_dct/<feed>',views.patient_send_feedback_abt_dct),
    path('patient_send_feedback_abt_dct_post',views.send_feedback_abt_dct_post),
    path('patient_photo_prediction',views.patient_photo_prediction),
    path('patient_symptom_selection',views.patient_symptom_selection),
    path('patient_user_profile', views.patient_user_profile),
    path('patient_view_booking',views.patient_view_booking),
    path('view_p_booking_post/',views.view_p_booking_post),

    path('patienthome/', views.patienthome),
    path('delete_pschedule/<int:id>', views.delete_pschedule),

    path('Pat_view_msg/<receiverid>', views.Pat_view_msg),
    path('chatview/<dlid>', views.chatview),
    path('doctor_insert_chat/<receiverid>/<msg>/<senid>', views.doctor_insert_chat),
    path('patient_insert_chat/<receiverid>/<msg>/', views.patient_insert_chat),
]
