# Generated by Django 2.0 on 2021-12-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('qual', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.department')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('feedback', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=10)),
                ('DOCTOR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.doctor')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=30)),
                ('BOOKING', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
                ('timeto', models.CharField(default='', max_length=15)),
                ('DEPARTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.department')),
                ('DOCTOR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.doctor')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sympt', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=150)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.login')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapplication.login'),
        ),
        migrations.AddField(
            model_name='chat',
            name='LOGINFROM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loginfrom', to='myapplication.login'),
        ),
        migrations.AddField(
            model_name='chat',
            name='LOGINTO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loginto', to='myapplication.login'),
        ),
        migrations.AddField(
            model_name='booking',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.user'),
        ),
    ]
